---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine
inputs:
  - name: repo
  - name: m2
outputs:
  - name: output
run:
  path: sh
  args:
    - -c
    - |
      cd repo
      ./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
      mv target/*.jar ../output/demo.jar
params:
  _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom
