---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: repo
  - name: repo-release
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - -c
  - |
    git config --global user.email "${GIT_EMAIL}"
    git config --global user.name "${GIT_NAME}"
    cd out
    shopt -s dotglob
    mv -f ../repo/* ./
    git remote add -f release ../repo-release
    git merge --no-edit release/release