---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine    
inputs:
  - name: repo
  - name: m2
run:
  path: sh
  args:
    - -c
    - |
      cd repo
      ./mvnw test -Dmaven.repo.local=../m2/rootfs/opt/m2
