resources:
  - name: tracker
    type: tracker
    source:
      token: {{tracker-token}}
      project_id: {{tracker-project-id}}
      tracker_url: https://www.pivotaltracker.com
  - name: repo-develop
    type: git
    source:
      uri: git@github.com:making/concourse-ci-demo.git
      branch: develop
      private_key: {{github-private-key}}
  - name: repo-master
    type: git
    source:
      uri: git@github.com:making/concourse-ci-demo.git
      branch: master
      private_key: {{github-private-key}}
  - name: version
    type: semver
    source:
      uri: git@github.com:making/concourse-ci-demo.git
      branch: version
      private_key: {{github-private-key}}
      file: version
      driver: git
      initial_version: 0.5.0
  - name: cf-prod
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: production
      skip_cert_check: true
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: Development
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: making/m2
#      username: {-{docker-username}}
#      password: {-{docker-password}}
#      email: {-{docker-email}}

jobs:
  - name: test-develop
    serial: true
    public: true
    plan:
      - aggregate:
        - get: repo
          resource: repo-develop
          trigger: true
        - get: m2
      - task: unit
        file: repo/ci/tasks/unit.yml
      - put: tracker
        params:
          repos:
          - repo
  - name: test-master
    serial: true
    public: true
    plan:
      - aggregate:
        - get: repo
          resource: repo-master
          trigger: true
        - get: m2
      - task: unit
        file: repo/ci/tasks/unit.yml

  - name: tag-master
    plan:
      - aggregate:
        - get:  repo
          resource: repo-master
          passed: [ test-master ]
        - get: version
        - get: m2
      - task: update-pom
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk
          inputs:
            - name: version
            - name: repo
            - name: m2
          outputs:
            - name: out
          run:
            path: /bin/bash
            args:
              - -c
              - |
                VERSION=`cat version/number`
                cd out
                shopt -s dotglob
                mv -f ../repo/* ./
                echo "Releasing $VERSION"
                ./mvnw versions:set -DnewVersion=$VERSION -Dmaven.repo.local=../m2/rootfs/opt/m2
                git config --global user.email "{{git-email}}"
                git config --global user.name "{{git-name}}"
                git add pom.xml
                git commit -m "Release $VERSION"
      - put: repo
        resource: repo-master
        params:
          repository: out
          tag: version/number

  - name: bump-version
    plan:
      - aggregate:
        - get:  repo
          resource: repo-master
          passed: [ tag-master ]
          trigger: true
        - get: version
          params: {bump: minor}
        - get: m2
      - task: update-pom
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk
          inputs:
            - name: version
            - name: repo
            - name: m2
          outputs:
            - name: out
          run:
            path: /bin/bash
            args:
              - -c
              - |
                VERSION=`cat version/number`-SNAPSHOT
                cd out
                shopt -s dotglob
                mv -f ../repo/* ./
                echo "Bump to Next Development Version ($VERSION)"
                ./mvnw versions:set -DnewVersion=${VERSION} -DallowSnapshots -Dmaven.repo.local=../m2/rootfs/opt/m2
                git config --global user.email "{{git-email}}"
                git config --global user.name "{{git-name}}"
                git add pom.xml
                git commit -m "Bump to Next Development Version ($VERSION)"
      - put: repo
        resource: repo-master
        params:
          repository: out
      - put: version
        params: {file: version/number}

  - name: merge-master-to-develop
    plan:
      - aggregate:
        - get: repo
          resource: repo-develop
        - get: repo-master
          passed: [ bump-version ]
          trigger: true
      - task: merge-master-to-develop
        file: repo/ci/tasks/merge-master-to-develop.yml
      - put: repo
        resource: repo-develop
        params:
          repository: out
  - name: deploy-develop
    serial: true
    public: true
    plan:
      - aggregate:
        - get: m2
        - get:  repo
          resource: repo-develop
          passed: [ test-develop ]
          trigger: true
      - task: build
        file: repo/ci/tasks/build.yml
      - put: cf-dev
        params:
          manifest: repo/manifest-dev.yml
          path: output/demo.jar
          current_app_name: concourse-ci-demo-dev
  - name: deploy-prod
    serial: true
    public: true
    plan:
      - aggregate:
        - get: m2
        - get:  repo
          resource: repo-master
          passed: [ tag-master ]
          trigger: true
      - task: build
        file: repo/ci/tasks/build.yml
      - put: cf-prod
        params:
          manifest: repo/manifest.yml
          path: output/demo.jar
          current_app_name: concourse-ci-demo

#  - name: init-m2
#    plan:
#      - get: repo
#        resource: repo-master
#      - task: build-m2
#        config:
#          platform: linux
#          image_resource:
#            type: docker-image
#            source:
#              repository: java
#              tag: 8-jdk-alpine
#          inputs:
#            - name: repo
#          outputs:
#            - name: to-push
#          run:
#            path: sh
#            args:
#            - repo/ci/tasks/m2.sh
#            - init
#      - put: m2
#        params:
#          import_file: to-push/rootfs.tar
#
#  - name: update-m2
#    plan:
#      - get: repo
#        resource: repo-master
#      - get: m2
#      - task: build-m2
#        config:
#          platform: linux
#          image_resource:
#            type: docker-image
#            source:
#              repository: java
#              tag: 8-jdk-alpine
#          inputs:
#            - name: repo
#            - name: m2
#          outputs:
#            - name: to-push
#          run:
#            path: sh
#            args:
#            - repo/ci/tasks/m2.sh
#      - put: m2
#        params:
#          import_file: to-push/rootfs.tar
